### PR TITLE
added deployment diagram

### PR DESCRIPTION
**Pull request by gnawnahtan**
Added PNG file of our deployment diagram.

Please click [this](https://github.com/calvin-cs262-fall2020-teamG/predestination-project/blob/project/deployment-diagram/Predestination%20Deployment%20Diagram%20v2.png) to view it

### CODE REVIEW

**Comment by gnawnahtan** [comment]
@kvlinden Hello, Prof. Vander Linden! Could you please review our deployment diagram and give us some feedback on how we can improve it?

**Comment by kvlinden** [comment]
This diagram looks generally good, but you should:

- Include container/nodes for NodeJS (in the Heroku node) and PostgresSQL (in the ElephantSQL node). Each contains the Predestination artifact you've got there.
- Include the stereotype annotations on the nodes ("<<client>>", "<<server>>") along with the names you already have. See the example on the class video.
- Label the arcs with the communication protocol being used (e.g., HTTP for the web service).

**Comment by ewalters47** [comment]
I've updated our deployment diagram with the suggestions from Prof. Vander Linden. We should go over these in our final meeting.

**Comment by ajs2440** [comment]
This looks good, I think it's time to merge although we weren't able to fully go over it one final time.

**Pull request merged**
